### PR TITLE
Visiting root application redirects to '/reminders'

### LINKED ISSUE #2: Adjust Root to Redirect to ‘/reminders’
When the user visits the root of the application, they should be redirected to '/reminders' and should see a list of all reminders on the page. This means making a hopefully small adjustment to your router.js file.

**Hot Tip**: This will make your previous test fail (if you had it passing). Make the necessary changes in the test(s).

### PR DESCRIPTION
**Pull request by esayler**
@martensonbj @Tman22 @chelletuerk 

## Purpose

Resolves #2 . When the user visits the root of the application, they should be redirected to `/reminders` and should see a list of reminders on that page. Updated `ember-cli` and dependencies to reflect ember v2.11.0 

## Approach

Make an index route to `/` and redirect directly to `/reminders`

#### Ember.js Routing
* [Ember Guides Routing - Redirection](http://guides.emberjs.com/v2.11.0/routing/redirection/)
* [Stack Overflow - Ember Testing route redirect](http://stackoverflow.com/questions/38903908/ember-testing-route-redirect)

#### Issues updating Ember.js
* [Faker.js - Github - Issues - The new return type of lorem.words is a breaking change #356](https://github.com/Marak/faker.js/issues/356)
* [ember-cli-mirage - Github - Issues - Acceptance test fails in PhantomJS #979](https://github.com/samselikoff/ember-cli-mirage/issues/979)
* [Ember CLI Mirage Changelog](https://github.com/samselikoff/ember-cli-mirage/blob/master/CHANGELOG.md)
* [ember-cli - Github - release notes - v2.11.0 - "I’m gonna need a hacksaw."](https://github.com/ember-cli/ember-cli/releases/tag/v2.11.0)
* [Ember CLI Docs](http://www.ember-cli-mirage.com/)
* [Testem - Github](https://github.com/testem/testem)
* [ember-cli-babel - Github](https://github.com/babel/ember-cli-babel)

#### `git cherry-pick`
* [git docs - `git cherry-pick`](https://git-scm.com/docs/git-cherry-pick)

### Open Questions and Pre-Merge TODOs

- [x] Figure out how to redirect from index route to `‘/reminders’` route
  - [x] Update `routes.js` to reflect both root `/` and `/reminders` routes
  - [x] Update `routes/index.js` to redirect immediately to `/reminders`
- [x] Create a home index route in the app
- [x] Use `beforeModel` or `afterModel` for transition to new route? 
- [x] Update tests to reflect that reminders now live on ‘/reminders’ route
- [x] Resolve issues with updating `ember-cli` and using `ember init`

#### 30/30 passing
- index route test `index-test.js`

### Follow-up tasks

- Issue #3 

#### Before

screenshot 2017-02-08 04 45 17

#### After

screen capture on 2017-02-08 at 17-29-47

### CODE REVIEW

File: app/routes/index.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  afterModel() {
```
Comment (martensonbj) [inline app/routes/index.js]: I'd use a `beforeModel()` hook here because we need the redirect to happen before it tries to grab a model - do you have a reason for using `afterModel()`?

File: app/routes/index.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+    this.transitionTo('reminders');
```
Comment (martensonbj) [inline app/routes/index.js]: Also just a comment but `transitionTo` will keep the '/' path in the browser history. If you never need to USE that path (like in no situation would a user hit the "back" button to get to the root page), i'd use `replaceWith` instead

File: mirage/factories/reminder.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import { Factory, faker } from 'ember-cli-mirage';
 
 export default Factory.extend({
-  title: () => faker.lorem.words().join(' ').capitalize(),
+  title: () => faker.lorem.words().capitalize(),
```
Comment (martensonbj) [inline mirage/factories/reminder.js:4]: Good catch :)

**Review by martensonbj — CHANGES_REQUESTED** [review]
Couple small things

File: app/routes/index.js (hunk 1 above)
Comment (esayler) [reply app/routes/index.js]: No real reason, thought we should grab the data first by using `beforeModel()`

File: app/routes/index.js (hunk 2 above)
Comment (esayler) [reply app/routes/index.js]: thanks, sounds good! 👍

File: mirage/factories/reminder.js (hunk 3 above)
Comment (esayler) [reply mirage/factories/reminder.js:4]: :1st_place_medal:

**Comment by esayler** [comment]
@martensonbj  @Tman22 Ok, we updated the route to use `replaceWith()` and `beforeModel()`!

**Review by martensonbj — APPROVED** [review]
